[versions]
corePlugins = "1.0.1"
financeTheme = "1.0.1"

[libraries]
corePlugins = { group = "vn.core.libs", name = "plugins", version.ref = "corePlugins" }
financeTheme = { group = "vn.finance.libs", name = "theme", version.ref = "financeTheme" }

[plugins]
